### PR TITLE
add HA Addon

### LINKED ISSUE #49: Is there already a HA_hcpy-addon, or can it at least be run directly under HA?
Hello everybody,
I have a Siemens oven which I would like to integrate locally into my Home Assistant (VM on a Synology DiskStation) without using the Home Connect Cloud.
I came across the Trammell Hudson's article about a year ago, but didn't know how to integrate it directly into HA.
It should be possible to run the Phyton scripts directly in HA, for example with [python_script](https://github.com/home-assistant/core/tree/dev/homeassistant/components/python_script) or [PythonScriptsPro](https://github.com/AlexxIT/PythonScriptsPro)?
Or what would be even better: Is there now a corresponding add-on (something like [HA_enoceanmqtt-addon](https://github.com/mak-gitdev/HA_enoceanmqtt-addon))?

### PR DESCRIPTION
**Pull request by pmagyar**
Resolves #49 

Addon Options:
image

Running Addon:
image

image

"Known Issues" (currently i would accept those issues):
- currently we have to manually copy devices.json to homeassistant_base/share/*
- in my case, the hostname in devices.json can´t resolved in the addon container because of missing FQDN. I have changed hostname to the IP address of the device

Note:
- After merge, we have to create a release with tag v0.1.0 ( should match the version in the addon config.yaml)
- I have not tested the build process for linux/armhf, linux/aarch64, linux/i386.... But maybe if there are any problems, we can fix it after merge.

ToDo:

- [x] add documentation how to install the addon -> https://github.com/hcpy2-0/hcpy/wiki/HomeAssistant-Addon

### CODE REVIEW

**Comment by pmagyar** [comment]
That´s a good idea! Yes we can add this in a new pr. 

 ok, take your time :)

**Comment by Oktonaut** [comment]
Wow Great work in such a short time... looks really good, my compliments!

However, when adding the repository I get an error message:
hcpy-addon-Reprositorie

To create the devices.json, the hc-login.py should be able to be executed during the initial installation or for adding new devices via the addon.

So that it is immediately clear what the addon is good for, I think it should be renamed "hcpy2mqtt" or a descriptive name.

**Comment by noxhirsch** [comment]
Thank you very much for your work on this!


> So that it is immediately clear what the addon is good for, I think it should be renamed "hcpy2mqtt" or a descriptive name.

I agree. I would go one step further and call the add-on something like "HomeConnect2MQTT".

@Oktonaut: I'd assume that this PR has to be merged before you can add the repository to the addon store (by the way: HACS is for integrations - not for addons)

**Comment by Oktonaut** [comment]
ok thanks for the info... then I'll just wait a bit until the PR is merged and a working version is available with which you can also create the devices.json.

**Comment by noxhirsch** [comment]
> Hope it will help and I would be happy if someone else could test it.

@pmagyar It took me some time, but I finally managed to install the addon and generate the devices.json. At first the addon could not connect to the dishwasher because the host was not found. When I then replaced the host entry in devices.json with the IP, this also worked. I have not yet established a connection with Home Assistant due to lack of time, but I was able to see the status and changes to the status on the MQTT server 👍

**Comment by pmagyar** [comment]
Hey @noxhirsch 
Thanks for your time and testing.
Glad to hear it's working.
I have currently documented the problem with the host name.
Maybe this will be solved if we generate the devices.json in the container...

**Comment by Meatballs1** [comment]
I wonder if it's mDNS resolution failing, or maybe an ipv6 issue (most of my devices have a ipv6 address)

**Comment by noxhirsch** [comment]
@Meatballs1 I just did some more tests: First I pinged the hostname on my windows machine with success - then I noticed that windows added `.local` to it. After I added `.local` to `host` in devices.json it worked with the hostname. I don't know if that depends on my setup (Unifi / all IPv4). Depending on this, either HomeConnect2MQTT can add the `.local` directly or only after a failed attempt.

**Comment by Meatballs1** [comment]
Sounds like it could be an mDNS issue, do you have .local set as your default suffix?

**Comment by Meatballs1** [comment]
It does sound like it's a mDNS issue as .local is specifically used for that. 

I wonder if adding avahi to container would help?

https://medium.com/@andrejtaneski/using-mdns-from-a-docker-container-b516a408a66b

**Comment by noxhirsch** [comment]
> Sounds like it could be an mDNS issue, do you have .local set as your default suffix?

In fact, "local" was specified as the domain name in my Unifi DHCP settings. However, nothing changed when I removed this and restarted / reconnected the devices.
I always thought hostname.local was the correct way to address a device. The default URL of HA is also homeassistant.local:8123 - not homeassistant:8123.

**Comment by Meatballs1** [comment]
This doesn't break the basic script or standard docker, I'm going to merge and then see if I can take a look at the DNS issues

**Comment by Meatballs1** [comment]
I think you will need to change the repo visibility @pmagyar 
image

**Pull request merged**
