### PR TITLE
Added pre-commit config

### PR DESCRIPTION
**Pull request by pmagyar**

### CODE REVIEW

**Comment by Meatballs1** [comment]
Softtabs? 👍

**Comment by Meatballs1** [comment]
Think this is reverting updates that are in main. I'll hold off doing any other changes as I don't want to merge into retabbed files 😱

**Comment by pmagyar** [comment]
sure :) its recommended in python (pep8).

**Comment by pmagyar** [comment]
@Meatballs1 can you review?

**Pull request merged**
